export enum Icons {
  Angular = 'icon-angular-large ',
  React = 'icon-reactjs-large ',
  Cpp = 'icon-cpp-large ',
  Typescript = 'icon-typescript-large ',
  Html = 'icon-html-large ',
  Css = 'icon-css-large ',
  Electron = 'icon-electronjs-large ',
  Node = 'icon-nodejs-large ',
  Nest = 'icon-nestjs-large ',
  Git = 'icon-git-large ',
  JSON = 'icon-json-large ',
  XML = 'icon-xml-large ',
  Unreal = 'icon-unreal-large ',
  Lua = 'icon-lua-large ',
}
